services:
  - type: web
    name: tharun-md
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: PAIRING_NUMBER
        sync: false
      - key: BOT_NAME
        value: 𝐓𝐡𝐚𝐫𝐮𝐧-𝐌𝐃
      - key: BOT_OWNER
        value: Tharun Prabhashwara
      - key: PREFIXES
        value: .,!,/
      - key: COMMAND_MODE
        value: public
      - key: TIMEZONE
        value: Asia/Colombo
      - key: PORT
        value: 5000
